spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: 123
    listener:
      simple:
        concurrency: 3
        max-concurrency: 10
        acknowledge-mode: auto

logging:
  level:
    org.springframework.amqp: INFO
    org.springframework.amqp.rabbit.listener: INFO
server:
  port: 8081